In [63]:
# 라이브러리 불러오기

import numpy as np

In [64]:
# np_print

def np_print(arr):
    text = '''
    type : %s
    shape : %s
    ndim : %s
    dtype : %s
    array data : \n %s''' % (type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

# 산술 연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) :dot()

In [3]:
# 🔴 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열

## 🔸 1) 1부터 10미만의 범위
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
## 🔸 2) 위의 데이터를 reshape를 통해 3x3 배열로 만듦

a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# 🔴 4이상 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성

b = np.arange(4,13).reshape(3,3)
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
# 🔴 10 ~ 21까지 3행 4열 형태로 만들기

c = np.arange(10, 22).reshape(3,4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## 1. 더하기

- 배열 + 배열
- np.add(arr1, arr2)
- 파이썬에서 배열끼리 더하면 원래는 연장을 해주는데, 얘는 배열끼리 더해줌
- 배열의 크기가 맞아야한다

In [13]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# 🔴 산술 연산자 1) +

a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [16]:
# 🔴 산술 연산자 2) np.add(a, b)

np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [17]:
# 🔴 구조가 다른 배열간의 산술 연산시 에러 발생

## 3x3 과 3x4의 형태
## ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

## 2. 빼기

- 배열 - 배열
- np.subtract(arr1, arr2)

In [19]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# 🔴 산술 연산자 1) -

a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [23]:
# 🔴 산술 연산자 2) np.subtract(a, b)

np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

## 3. 나누기
- 배열 / 배열
- np.divide(arr1, arr2)

In [24]:
# 🔴 산술 연산자 1) /

a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [26]:
# 🔴 산술 연산자 2) np.divide(a, b)
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

## 4. 곱하기

- 배열 * 배열
- np.multiply(arr1, arr2)

In [27]:
# 🔴 산술 연산자 1) *
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [28]:
# 🔴 산술 연산자 2) np.multiply(a, b)
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

## 5. 지수곱 표현

- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# 🔴 a를 지수함수로 바꾸기

np.exp(a)

## 2.71의 1제곱, 2제곱, 3제곱, ... 9제곱
## 2.7, 7.3, 20, 54, 148, ... 8103

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

## 6. 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [32]:
# 🔴 배열을 넣으면 모든 제곱근을 구해줌

np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

## 7. 내적(행렬곱)

- np.dot(a,b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [33]:
# 🔸 그냥 *으로 하면 => 좌표끼리 곱한다.

a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [34]:
# 🔴 행렬곱은 .dot을 사용

np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

## 8. Numpy 배열 연산

###  비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [35]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# 🔴 두 배열 요소에 대하여 값이 동일한지를 비교

## 반환 : 각 요소마다의 비교 결과 (True, False)가 배열로 표현된다.

## 같은 좌표에 있는 애들끼리 같은가?
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [37]:
np_print(a == b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : bool
    array data : 
 [[False False False]
 [False False False]
 [False False False]]


In [38]:
# 🔴 두 배열 요소에 대하여 값이 다른지 비교
np_print(a != b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : bool
    array data : 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
# 🔴 두 배열 요소에 대해 크기 비교

a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
# 🔴 두 배열이 완전히 일치하는지 여부만 조회
## 하나의 True, False로 반환

np.array_equal(a, b)

False

In [43]:
np.array_equal(a, a)

True

## Numpy 배열 연산(이어서)

### 집계 함수

- Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
- 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
- axis
    - axis = None <br>
    - 전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
            - a라는 요소와 b라는 요소가 얼마나 상관이 있는지
                - '키'가 커지면 대체로 '체중'이 크다 (=> 상관도 0.7 정도)
                - a라는 요소에 따라 b가 무조건 커지면 (=> 상관도 1)
                - a라는 요소에 따라 b가 무조건 작아지면 (=> 상관도 0)
            
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()
            - 중복된 값은 무조건 하나로 계산

In [44]:
# 🔴 사용할 배열 객체 확인

np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
# 🔴 합계 - 전체 기준 => 모든 요소에 대한 합

## 🔸 1) 배열 타입의 메서드 : arr.sum()

### axis를 주지 않았으므로 배열 전체(9개)를 더한 것
a.sum()

45

In [48]:
## 🔸 2) numpy함수 : np.sum(arr)

np.sum(a)

45

In [50]:
# 🔴합계 - row, 가로출별 합산

## 🔸 메서드, np함수의 파라미터 값 : axis = 1로 주면 됨
## 결과값 : [0번row합, 1번row합, 2번 row합]

print(c)
print(c.sum(axis=1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[46 62 78]


In [52]:
# 🔴 합계 - column, 세로줄별 합산

## 🔸 메서드, np함수의 파라미터 값 : axis=0으로 주면 됨
## 결과값 : [0번째 column합, 1번째 column합 ...]

print(c)
print(c.sum(axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[42 45 48 51]


In [53]:
# 🔴 최소값 - 전체 기준

## 🔸 1) 배열 타입의 메서드 : arr.min()
c.min()

10

In [54]:
## 🔸 2) numpy함수 : np.min(arr)
np.min(c)

10

In [55]:
## 🔸 (참고) 파이썬 리스트에서 최소값 찾기
x = [1, 2, 3, 4]
min(x)

1

In [60]:
# 🔴 최소값 - 각 가로축(row)별 최소값 찾기
## 결과값 : [0번째 row최소값, 1번째 row최소값 ...]

print(c)
print(c.min(axis=1))
print(np.min(c, axis=1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 14 18]
[10 14 18]


In [62]:
# 🔴 최소값 - 각 세로축(column)별 최소값 찾기
## 결과값 : [0번째 컬럼값, 1번째 컬럼값 ...]

print(c)
print(c.min(axis=0))
print(np.min(c, axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 11 12 13]
[10 11 12 13]
