In [3]:
# 라이브러리 불러오기

import numpy as np

In [4]:
# np_print

def np_print(arr):
    text = '''
    type : %s
    shape : %s
    ndim : %s
    dtype : %s
    array data : \n %s''' % (type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

# ⬛ 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환 💛 
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 인덱스번호'만' 준다.

In [5]:
# 🔴 1차원 배열 생성

x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int32
    array data : 
 [0 1 2 3 4]


In [6]:
# 🔴 기존 파이썬 문법으로 순번 뒤집기

x[::-1]

array([4, 3, 2, 1, 0])

In [7]:
# 🔴 오름차순 정렬 테스트용 난수 배열 만들기

# 0 이상 9이하 숫자 5개를 난수 생성으로 만들어서 찍어주세요

a = np.random.randint(0, 10, 5)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int32
    array data : 
 [8 8 1 4 6]


In [8]:
# 🔴 오름차순 정렬 1) => np.sort(자료) : 원본 자료가 바뀌지는 않음

print(np.sort(a))
print(a)

[1 4 6 8 8]
[8 8 1 4 6]


In [9]:
# 🔴 오름차순 정렬 2) 자료.sort() -> 원본자료가 바뀜
a.sort()

In [10]:
print(a)

[1 4 6 8 8]


In [11]:
# 🔴 난수 생성

b = np.random.randint(0, 10, 5)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int32
    array data : 
 [5 7 8 6 9]


In [12]:
# 🔴 np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해서는
#     현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌

np.argsort(b)

## 0 > 8
## 1 > 1
## 2 > 7
## 3 > 3
## 4 > 9

## array([1, 3, 2, 0, 4], dtype=int64)
## 1, 3, 7, 8, 9

array([0, 3, 1, 2, 4], dtype=int64)

In [13]:
# 🔴 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성

a = np.random.random((3,3))
b = np.random.random((3,3))

## 혹은 np.random.random(9).reshape(3,3)

In [14]:
print(a)
print(b)

[[0.30508701 0.01491793 0.37683066]
 [0.83125634 0.93629603 0.61567669]
 [0.98612645 0.09059088 0.13094195]]
[[0.58888224 0.6475997  0.59896852]
 [0.65660719 0.90149767 0.03600726]
 [0.86866931 0.29983833 0.98666861]]


##### 예) 2차원 배열의 경우

- 기본값 axis = -1
- 현재 배열의 axis = 0, 1
- 마지막 axis = 1 (열 별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [15]:
# 🔴 기본 방향 (axis = -1) => 행별 정렬

np_print(a)
np.sort(a)

## 아홉개가 전체적으로 되는 것이 아니라 ----> 오른쪽 방향으로 한 줄 한줄씩 세 줄이 정렬이 되는 것


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[0.30508701 0.01491793 0.37683066]
 [0.83125634 0.93629603 0.61567669]
 [0.98612645 0.09059088 0.13094195]]


array([[0.01491793, 0.30508701, 0.37683066],
       [0.61567669, 0.83125634, 0.93629603],
       [0.09059088, 0.13094195, 0.98612645]])

##### axis = 0 (병렬 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [16]:
# 🔴 기본 방향 (axis = 0) => 열별 정렬

np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[0.30508701 0.01491793 0.37683066]
 [0.83125634 0.93629603 0.61567669]
 [0.98612645 0.09059088 0.13094195]]


array([[0.30508701, 0.01491793, 0.13094195],
       [0.83125634, 0.09059088, 0.37683066],
       [0.98612645, 0.93629603, 0.61567669]])

# ⬛ 인덱싱(Indexing), 슬라이싱(Slicing)

## 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [17]:
# 🔴 0 ~ 23 구간으로 1씩 증가하는 값을 아이템으로 가지는 1차원 배열을 생성하세요

arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    ndim : 1
    dtype : int32
    array data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [18]:
# 🔸 1차원 배열 인덱싱 : 1차원 인덱스 요소 접근

arr1[1]

1

In [19]:
# 🔸 1차원 배열 인덱싱 : 마지막 요소 접근

arr1[-1]

23

In [20]:
# 🔸 1차원 배열 인덱싱을 통한 값 수정

arr1[-1] = 100
print(arr1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22 100]


In [21]:
# 🔴 배열 arr1을 이용해 4 * 6 형태의 2차원 배열 arr2 만들기

arr2 = arr1.reshape(4,6)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (4, 6)
    ndim : 2
    dtype : int32
    array data : 
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]


In [22]:
# 🔸 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]

## 💛 파이썬에서는 안되지만 numpy에서는 됨

## * 하나의 행에 접근 : 1행
print(arr2[0])

[0 1 2 3 4 5]


In [23]:
## * 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접근
### 반환값 : 1d array
### 행은 전체범위, 열은 0번째

arr2[:, 0]

array([ 0,  6, 12, 18])

In [24]:
## * 하나의 값에 접근
### 3행 3열에 접근(0번쨰부터 세서 3행)

print(arr2)
print(arr2[2,2])

[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
14


In [25]:
# 🔸 여러개의 행 조회 (2차원 배열로 조회)

## 0번째, 3번째 행이 출력됨

print(arr2)
print("--------------------------")
print(arr2[[0,3]])

[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
--------------------------
[[  0   1   2   3   4   5]
 [ 18  19  20  21  22 100]]


In [26]:
# 🔸 여러개의 열 조회(모든 행)

print(arr2)
print(arr2[:,[0,2]])

## 행은 다 잡고, 그 중에서 0, 2번째 열만 조회

[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
[[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]]


In [27]:
# 🔸 여러개의 열 조회 (특정 행)

print(arr2)
print(arr2[0:2,[0,2]])

[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
[[0 2]
 [6 8]]


In [28]:
# 🔸 2차원 배열 인덱싱을 통한 값 수정

## 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하려는 값을 스칼라값으로 전달
## 서로 다른 값으로 수정 : 배열 요소 개수에 맞춰서 전달

## * 하나의 값을 수정하는 예시 (모두 바뀌어 버림)
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [29]:
## * 단일 값이 아닌 여러 값을 대입하고 싶다면? => 같은 길이의 배열을 넣으면 된다.

arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [30]:
# 🔴 3차원 배열 생성

## 구조 : 2개의 층(면), 4행 3열

## np.arange() => 0 ~ 23까지 24개를 집어넣고, 3차원으로 재조정해보세요

arr3 = np.arange(24).reshape((2, 4, 3))

np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (2, 4, 3)
    ndim : 3
    dtype : int32
    array data : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [31]:
# 🔸 3차원 배열 인덱싱 : arr[면, 행, 열]

## ◾ 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
## ◾ 0번째 면, 첫 번째 행에 접근

arr3[0,1]

array([3, 4, 5])

In [33]:
## ◾ 1번째 면, 2번째 행, 2번 열에 접근

arr3[1, 2, 2]

20

In [34]:
# 🔸 3차원 배열 역시, 배열 인덱싱으로 값 수정이 가능합니다.

## ◾ 스칼라값을 이용한 변경
## arr3의 2번면(0번째부터 세면 1번째)을 0으로 일괄 수정해주세요

arr3[1] = 0
print(arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [35]:
## ◾ 하나의 면에 대해 서로 다른 값으로 수정 : 요소의 값을 같은 구조, 개수로 전달
## [1, 1]의 값이 현재 0, 0, 0인데 각각 1, 2, 3으로 바꿔주세요

arr3[1,1] = [1, 2, 3]
print(arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 0  0  0]
  [ 0  0  0]]]


In [36]:
## ◾ 한 면을 통째로 바꾸고 싶다면 같은 크기의 2차원 배열을 대입해줍니다.

arr3[0] = [[10, 20, 30],
           [40, 50, 60],
           [0, 0, 0],
           [0, 0, 0]]

print(arr3)

[[[10 20 30]
  [40 50 60]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 0  0  0]
  [ 0  0  0]]]


In [37]:
## ◾ 여러개의 인덱싱을 배열로 전달

## (행0, 열0), (행1, 열1), (행2, 열2)

## 3차원 배열일 경우에 : [페이지, [[0, 1, 2], [0, 1, 2]]]
## arr3[면, 행, 열] -> 만약 여러 단위를 조회할 때는 이중 리스트로 입력
## 삼중 리스트 입력시 이중리스트 요소를 반복

print(arr3[0])
print("------------------")
print(arr3[0, [[0, 1 ,2], [0, 2, 3]]])

## 해석 : 0번째 면을 가지고 오는데, 같은 범위를 두 번 지정한 (0, 1, 2)와 (0, 2, 3)의 조합으로 하나씩 보겠다
## 하나의 면에 여러 번 지목할 수 있는 것. (3차원으로 넣어주어야 함)

## 💛 2차원 배열 조회시 2차원으로, 3차원 배열 조회시 3차원으로 넣어주어야 함.

[[10 20 30]
 [40 50 60]
 [ 0  0  0]
 [ 0  0  0]]
------------------
[[[10 20 30]
  [40 50 60]
  [ 0  0  0]]

 [[10 20 30]
  [ 0  0  0]
  [ 0  0  0]]]


In [39]:
# ◾ 내부 요소 인덱싱시 일반 리스트를 사용하는 경우

## 줄 단위로 가져오는게 아니라 내부 요소 하나하나를 단위로 가져옴

arr3[0, [0, 1, 2], [0, 1, 2]]

### 0번째의 면에서 0번째의 0번째, 1번째의 1번째, 2번째의 2번째를 가져온다.

array([10, 50,  0])

## 2. 슬라이싱 : 여러 개의 요소에 대해 참조

- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [40]:
# 🔴 0부터 23까지 1씩 증가하는 정수값을 가지는 1차원 배열을 변수 a에 저장해서 조회해주세요

a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    ndim : 1
    dtype : int32
    array data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [42]:
# 🔴 1차원 배열 슬라이싱 : 1번부터 4번까지 접근

a[1:5]

array([1, 2, 3, 4])

In [47]:
# 🔴 1번째 인덱스부터 14번째 인덱스까지 2씩 증가시키며 접근

a[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [53]:
# 🔴 2차원 배열(6 * 4 )로 a의 형태를 바꿔 변수 b에 저장하고 화면에 찍기

b = a.reshape(6,4)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (6, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [58]:
# 🔴 2차원 배열 슬라이싱 : 1행부터 4행까지 접근

## 🔸 2d_array[행(:열:간격)]

b[1:5]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
## 🔸 1행부터 4행에 대해서 2열부터 3열까지 접근 (콤마로 구분 => 행범위, 열범위)

b[1:5,2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [60]:
# 🔴 2차원 배열 슬라이싱을 통한 값 수정

## 🔸 1행부터 4행에 대해 2열부터 3열까지의 모든 배열에 대해서 수정

s_arr = b[1:5, 2:]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [64]:
## 🔸 0번째 행과 마지막 열을 제외한 모든 값을 99로 수정

s_arr[1:4, 0] = 99
np_print(s_arr)


    type : <class 'numpy.ndarray'>
    shape : (4, 2)
    ndim : 2
    dtype : int32
    array data : 
 [[ 6  7]
 [99 11]
 [99 15]
 [99 19]]


In [65]:
## 💛 (주의!) b를 활용한 s_arr의 값을 바꾸면 '얕은 복사'이기 때문에 b값(원본배열)까지 변한다.
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [67]:
# 🔴 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열(컬럼)에 대한 인덱싱

## 🔸 step1. 전체 행에 대해서 접근(콜론 : 만 써주면 됨)

b[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [68]:
## 🔸 step2. 여러개의 열 인덱싱 배열 전달(:, 내가 원하는 열에 대해 리스트 형식으로)

## 🔸 b의 전체 행 + 1, 3번 열을 조회해주세요

b[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

### 연습문제

아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left'>

In [71]:
data = [[1, 2, 3, 4],
        [70, 97, 45, 56],
        [87, 84, 33, 67],
        [46, 80, 75, 78]]

arr = np.array(data)
print(arr)

[[ 1  2  3  4]
 [70 97 45 56]
 [87 84 33 67]
 [46 80 75 78]]


In [80]:
# 영어 성적을 기준으로 오름차순 정렬

In [ ]:
# 영어 성적을 기준으로 오름차순 정렬 순위(argsort()기능 사용하기)

In [82]:
np.argsort(arr[1])

array([2, 3, 0, 1], dtype=int64)

In [83]:
arr[:, [2, 3, 0, 1]]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

In [84]:
arr[:, np.argsort(arr[1])]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])