In [65]:
# 라이브러리 불러오기

import numpy as np

In [66]:
# np_print

def np_print(arr):
    text = '''
    type : %s
    shape : %s
    ndim : %s
    dtype : %s
    array data : \n %s''' % (type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

# 산술 연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) :dot()

In [67]:
# 🔴 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열

## 🔸 1) 1부터 10미만의 범위
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
## 🔸 2) 위의 데이터를 reshape를 통해 3x3 배열로 만듦

a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
# 🔴 4이상 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성

b = np.arange(4,13).reshape(3,3)
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
# 🔴 10 ~ 21까지 3행 4열 형태로 만들기

c = np.arange(10, 22).reshape(3,4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## 1. 더하기

- 배열 + 배열
- np.add(arr1, arr2)
- 파이썬에서 배열끼리 더하면 원래는 연장을 해주는데, 얘는 배열끼리 더해줌
- 배열의 크기가 맞아야한다

In [13]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# 🔴 산술 연산자 1) +

a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [16]:
# 🔴 산술 연산자 2) np.add(a, b)

np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [17]:
# 🔴 구조가 다른 배열간의 산술 연산시 에러 발생

## 3x3 과 3x4의 형태
## ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

## 2. 빼기

- 배열 - 배열
- np.subtract(arr1, arr2)

In [19]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# 🔴 산술 연산자 1) -

a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [23]:
# 🔴 산술 연산자 2) np.subtract(a, b)

np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

## 3. 나누기
- 배열 / 배열
- np.divide(arr1, arr2)

In [24]:
# 🔴 산술 연산자 1) /

a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [26]:
# 🔴 산술 연산자 2) np.divide(a, b)
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

## 4. 곱하기

- 배열 * 배열
- np.multiply(arr1, arr2)

In [27]:
# 🔴 산술 연산자 1) *
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [28]:
# 🔴 산술 연산자 2) np.multiply(a, b)
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

## 5. 지수곱 표현

- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# 🔴 a를 지수함수로 바꾸기

np.exp(a)

## 2.71의 1제곱, 2제곱, 3제곱, ... 9제곱
## 2.7, 7.3, 20, 54, 148, ... 8103

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

## 6. 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [32]:
# 🔴 배열을 넣으면 모든 제곱근을 구해줌

np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

## 7. 내적(행렬곱)

- np.dot(a,b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [33]:
# 🔸 그냥 *으로 하면 => 좌표끼리 곱한다.

a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [34]:
# 🔴 행렬곱은 .dot을 사용

np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

## 8. Numpy 배열 연산

###  비교 연산

1) 요소
- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=

2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [35]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# 🔴 두 배열 요소에 대하여 값이 동일한지를 비교

## 반환 : 각 요소마다의 비교 결과 (True, False)가 배열로 표현된다.

## 같은 좌표에 있는 애들끼리 같은가?
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [37]:
np_print(a == b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : bool
    array data : 
 [[False False False]
 [False False False]
 [False False False]]


In [38]:
# 🔴 두 배열 요소에 대하여 값이 다른지 비교
np_print(a != b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : bool
    array data : 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
# 🔴 두 배열 요소에 대해 크기 비교

a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
# 🔴 두 배열이 완전히 일치하는지 여부만 조회
## 하나의 True, False로 반환

np.array_equal(a, b)

False

In [43]:
np.array_equal(a, a)

True

## Numpy 배열 연산(이어서)

### 집계 함수

- Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
- 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
- axis
    - axis = None <br>
    - 전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
            - a라는 요소와 b라는 요소가 얼마나 상관이 있는지
                - '키'가 커지면 대체로 '체중'이 크다 (=> 상관도 0.7 정도)
                - a라는 요소에 따라 b가 무조건 커지면 (=> 상관도 1)
                - a라는 요소에 따라 b가 무조건 작아지면 (=> 상관도 0)
            
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()
            - 중복된 값은 무조건 하나로 계산

In [44]:
# 🔴 사용할 배열 객체 확인

np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
# 🔴 합계 - 전체 기준 => 모든 요소에 대한 합

## 🔸 1) 배열 타입의 메서드 : arr.sum()

### axis를 주지 않았으므로 배열 전체(9개)를 더한 것
a.sum()

45

In [48]:
## 🔸 2) numpy함수 : np.sum(arr)

np.sum(a)

45

In [50]:
# 🔴합계 - row, 가로출별 합산

## 🔸 메서드, np함수의 파라미터 값 : axis = 1로 주면 됨
## 결과값 : [0번row합, 1번row합, 2번 row합]

print(c)
print(c.sum(axis=1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[46 62 78]


In [52]:
# 🔴 합계 - column, 세로줄별 합산

## 🔸 메서드, np함수의 파라미터 값 : axis=0으로 주면 됨
## 결과값 : [0번째 column합, 1번째 column합 ...]

print(c)
print(c.sum(axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[42 45 48 51]


In [53]:
# 🔴 최소값 - 전체 기준

## 🔸 1) 배열 타입의 메서드 : arr.min()
c.min()

10

In [54]:
## 🔸 2) numpy함수 : np.min(arr)
np.min(c)

10

In [55]:
## 🔸 (참고) 파이썬 리스트에서 최소값 찾기
x = [1, 2, 3, 4]
min(x)

1

In [60]:
# 🔴 최소값 - 각 가로축(row)별 최소값 찾기
## 결과값 : [0번째 row최소값, 1번째 row최소값 ...]

print(c)
print(c.min(axis=1))
print(np.min(c, axis=1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 14 18]
[10 14 18]


In [62]:
# 🔴 최소값 - 각 세로축(column)별 최소값 찾기
## 결과값 : [0번째 컬럼값, 1번째 컬럼값 ...]

print(c)
print(c.min(axis=0))
print(np.min(c, axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 11 12 13]
[10 11 12 13]


In [72]:
# 🔴 최대값 - 전체 기준

## 🔸 1) 배열 타입의 메서드 : arr.max()
c.max()

21

In [73]:
## 🔸 2) numpy 함수 : np.max(arr)
np.max(c)

21

In [75]:
# 🔴 최대값 - 가로축 기준 (row)

## 🔸 1) 배열 타입의 메서드 : arr.max(axis=1)
print(c)
c.max(axis=1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([13, 17, 21])

In [76]:
## 🔸 2) numpy 함수

print(c)
np.max(c, axis=1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([13, 17, 21])

In [79]:
# 🔴 최대값 - 세로축 기준 (column)

## 🔸 1) 배열 타입의 메서드 : arr.max(axis=0)
print(c)
print(c.max(axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[18 19 20 21]


In [80]:
## 🔸 2) numpy 함수

print(c)
print(np.max(c, axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[18 19 20 21]


In [81]:
# 🔴 누적합계 - 전체 기준

## 🔸 1) 배열 타입의 메서드 : arr.cumsum()

print(c)
print(c.cumsum())

## 10, 10+11, 10+11,+12 ... , 10+11+...+20+21

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[ 10  21  33  46  60  75  91 108 126 145 165 186]


In [82]:
## 🔸 2) numpy함수 : np.cumsum(arr)

np.cumsum(c)

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165, 186],
      dtype=int32)

In [85]:
# 🔴 누적합계 - 가로축 (row) 기준

## 🔸 1) 배열 타입의 메서드 : arr.cumsum(axis=1)
print(c.cumsum(axis=1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]


In [87]:
## 🔸 2) numpy함수 : np.cumsum(arr, axis=1)
print(np.cumsum(c, axis=1))

[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]


In [88]:
# 🔴 누적합계 - 세로축 (column) 기준

## 🔸 1) 배열 타입의 메서드 : arr.cumsum(axis=0)
print(c.cumsum(axis=0))

[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]


In [89]:
## 🔸 2) numpy함수 : np.cumsum(arr, axis=0)
print(np.cumsum(c, axis=0))

[[10 11 12 13]
 [24 26 28 30]
 [42 45 48 51]]


In [92]:
# 🔴 평균 - 전체 데이터 기준

## 🔸 1) 배열 타입의 메서드 : arr.mean()
c.mean()

15.5

In [93]:
## 🔸 2) numpy 함수 : np.mean(arr)
np.mean(c)

15.5

In [97]:
# 🔴 평균 - 가로축 (row) 기준

## 🔸 1) 배열 타입의 메서드 : arr.mean(axis=1)
print(c)
c.mean(axis=1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([11.5, 15.5, 19.5])

In [98]:
## 🔸 2) numpy 함수 : np.mean(arr, axis=1)
print(c)
np.mean(c, axis=1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([11.5, 15.5, 19.5])

In [99]:
# 🔴 평균 - 세로축 기존(column) 기준

## 🔸 1) 배열 타입의 메서드 : arr.mean(axis=0)
print(c)
c.mean(axis=0)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([14., 15., 16., 17.])

In [100]:
## 🔸 2) numpy 함수 : np.mean(arr, axis=0)
print(c)
np.mean(c, axis=0)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([14., 15., 16., 17.])

In [104]:
# 🔴 중앙값 - 전체 기준

## 중앙값 : 단순히 크시 순으로 나열했을때, 중앙에 위치하는 값(인덱스 번호 = 중간에 있는)

## ❓ Q) 근데 여기서 15.5라는 값이 없는데 왜 15.5가 나올까?
## ❗ A) 1(첫 인덱스) + 12(마지막 인덱스) 를 2로 나누면 6.5번이다
##    요소가 홀수개면 중앙값을 얻는것이 쉽지만, 
##    (정렬이 되어 있을 때) 짝수개인 경우는 순번으로 나타낸 후 가운데 두개(15+16)를 더해서 2를 나눈다.

## 🔸 1) numpy 함수 : np.median(c)
print(c)
np.median(c)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


15.5

In [105]:
## 🔸 2) arr.median()을 직접 호출할 수 없음.
## AttributeError: 'numpy.ndarray' object has no attribute 'median'
c.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [107]:
## 🔸 a 를 가지고(9개) 중앙값을 구하면 원본에 있는 숫자로 잡힌다.

print(a)
np.median(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0

In [112]:
# 🔴 중앙값 - 가로축 기준

print(a)
print(np.median(a, axis=1))

print(c)
print(np.median(c, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 5. 8.]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[11.5 15.5 19.5]


In [113]:
# 🔴 중앙값 - 세로축 기준

print(a)
print(np.median(a, axis=0))

print(c)
print(np.median(c, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[14. 15. 16. 17.]


In [ ]:
# 🔴 상관계수 : 두 데이터간의 상관관계(양/음의 상관관계)  💛중요💛

## 🔸 numpy 함수 : np.corrcoef(arr1, arr2)

In [114]:
### * 사용할 데이터 세팅

x = np.array([163, 175, 181, 155, 157, 167, 178, 170])
y = np.array([52, 70, 69, 48, 43, 70, 81, 75])

In [115]:
print(x)
print(y)

[163 175 181 155 157 167 178 170]
[52 70 69 48 43 70 81 75]


In [117]:
### * 자기 자신을 대상으로 한 상관관계

np.corrcoef(x, x)

array([[1., 1.],
       [1., 1.]])

In [119]:
### * 서로 다른 배열의 상관관계 matrix

#### 결과 : 대칭형 매트릭스 (대각선을 경계로 상위, 하위 삼각형 중 하나만 해석해도 된다.)
####      : 오른쪽 아래로 향하는 대각선은 자기 자신과의 상관관계(항상 1)

print(x)
print(y)
print("----")
np.corrcoef(x, y)

[163 175 181 155 157 167 178 170]
[52 70 69 48 43 70 81 75]
----


array([[1.        , 0.85607253],
       [0.85607253, 1.        ]])

- 위의 결과 해석하기

    - 강한 상관관계가 있음
    
    
    - 0.3 미만  : 관계 없음
    - 0.3 ~ 0.7 : 관계 있음
    - 0.8 ~     : 강한 상관관계
    
    
    - 키가 1 정도 올라가면 체중은 0.85 정도 올라가는 경향

In [120]:
### * numpy에서는 3개 요소를 상관관계로 구할 수 없다.

#### 상관 관계는 원래 2개 요소 간의 관계만 구할 수 있다.

z = np.array([0.3, 0.5, 0.6, 0.8, 1.3])

In [122]:
np.corrcoef(x, y, z)

## ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [123]:
# 🔴 표준편차 - 전체 데이터 기준

## 🔸 1) 배열 타입 메서드 : arr.std()
## 🔸 2) numpy 함수 : np.std(arr)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
a.std()

## 2.5 ~ 7.5의 데이터가 나올 확률이 대충 70%

2.581988897471611

#### (참고) 데이터가 퍼져있는 정도를 나타내는 개념

1. 편차(std/sd) : 단위에 대한 보정이 들어가 있지 않아서 상대적인 비교가 어려움
2. 변동계수(cv) : 편차 / 평균
    - 두 개 이상의 변수(서로 다른 단위를 사용하는 경우)에 대해 데이터가 퍼져있는 정도를 파악하는 경우

In [126]:
# 🔴 a 데이터 생성

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 🔸 결과는 위와 같은데 다른 코드 => a = np.arange(1,10).reshape(3,3)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
# 🔸 표준 편차 row기준(가로줄)

print(a)
a.std(axis=1)

## 표준편차는 평균과는 상관없이 평균과 얼마나 떨어져있는지를 구하는 것

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([0.81649658, 0.81649658, 0.81649658])

In [129]:
# 🔸 표준 편차 columns 기준(세로줄)

print(a)
a.std(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

In [130]:
# 🔴 고유값 : 전체 값에 적용

## 🔸 numpy 함수 : np.unique(arr)

np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
d = np.array([1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 6, 6, 7])
np.unique(d)

array([1, 2, 3, 4, 5, 6, 7])

In [132]:
# 🔴 난수 패턴 고정

np.random.seed(1000)

In [140]:
# 🔴 0이상 3 이하의 정수 값을 가지는 3행 3열 배열 생성
## hint : randint를 쓰세요

d = np.random.randint(0, 4, (3,3))
np_print(d)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[0 3 2]
 [1 2 1]
 [3 2 3]]


In [141]:
## 🔸 d에 유니크를 걸면?

np.unique(d)

array([0, 1, 2, 3])

In [143]:
# 🔸 고유값 - 가로축

print(d)
print(np.unique(d, axis=1))

## 가로에서 [0, 3, 2]를 고유한 하나로 보는 것
## 만약 [0, 3, 2] [0, 3, 2] [0, 1, 1] => [0, 3, 2], [0, 1, 1]만 남는 것

[[0 3 2]
 [1 2 1]
 [3 2 3]]
[[0 2 3]
 [1 1 2]
 [3 3 2]]


In [144]:
# 🔸 고유값 - 세로축

print(d)
print(np.unique(d, axis=0))

[[0 3 2]
 [1 2 1]
 [3 2 3]]
[[0 3 2]
 [1 2 1]
 [3 2 3]]


In [145]:
## 🔸 범위 줄여서 다시 하나 만들어 봄

e = np.random.randint(0, 2, (3,3))
print(e)

[[1 1 1]
 [1 1 0]
 [1 1 0]]


In [148]:
print(e)
print("--------------")
print(np.unique(e, axis=1))
print("--------------")
print(np.unique(e, axis=0))

[[1 1 1]
 [1 1 0]
 [1 1 0]]
--------------
[[1 1]
 [0 1]
 [0 1]]
--------------
[[1 1 0]
 [1 1 1]]


### 브로드캐스팅(BroadCasting)

- 서로 다른 구조(shape)를 가진 배열에 대해 연산을 수행할 때 구조를 맞추는 과정
    - 구조가 다를 때도 가능하지만, 몇 가지 규칙 하에서만 가능
    
    
- 배열과 스칼라값 간의 연산
    - 스칼라값 : 일반 숫자 하나
    
    
- 배열과 배열 간의 연산


- 브로드캐스팅 규칙 : 축의 길이가 일치하거나 둘 중 하나의 길이가 1인 두 배열에 대해 호환성을 가짐


<img src='img/broadcast.png' width='600' height='400' align='left'>

- 1. 변의 길이가 일치하는 경우


- 2. 한쪽 변이 일치하고, 나머지 한 쪽 변이 1이면 밑으로 복사해줌
    - (4,3) + (1,3) => (4,3) + (4,3)


- 3. 서로 길이가 1인 변이 다른 경우는, 양쪽 모두를 늘려서 같은 크기로 만든다.
    - (4,1) + (1,3) => (4,3) + (4,3)


In [149]:
# 🔴 사용할 배열 객체 다시 확인

np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [151]:
## 🔸 양 변의 길이가 일치하는 경우

a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

#### 1. 배열과 값 (single value, scala)

- 스칼라 값을 배열의 구조와 동일한 배열로 변형하여 연산 수행

In [154]:
# 🔴 구조가 다른 배열간의 연산

## a 배열의 모든 요소에 각각 10씩 더하기
## 스칼라값 = 단일 값

print(a)
print(a + 10)

## 원래는 다른 자료형간의 더하기는 안되는데 얘는 됨

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [155]:
# 🔴 스칼라 -> 배열 변형
## 3행 3열 구조에 모든 요소가 10인 배열 요소 생성

### a가 3x3 형태인데, 나중에 형태가 몇*몇이 올지 모르니 배열 자체를 넣어 크기를 자동으로 구하게 처리
### 그냥 3x3으로 고정하고 싶다면 scalar_arr = np.full_like((3,3), 10)으로 만들면 됨

scalar_arr = np.full_like(a, 10)
np_print(scalar_arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [156]:
# 🔴 스칼라값을 직접 더하나 or 해당 숫자가 들어간 배열을 만들어 더하나 차이가 없음

a + scalar_arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### 2. 서로 다른 구조의 배열

- 행, 열의 최대 길이를 기준으로 구조를 생성한 배열로 변형하여 연산 수행
- 확장된 행, 열에 대해서 기존 배열과 동일한 데이터로 구성



- 조건 : 한 쪽이 1이어야함

In [161]:
# 🔴 1행 4열의 구조에서 1, 2, 3, 4를 값으로 가지는 배열 x 생성

x = np.array([1, 2, 3, 4]).reshape(1,4)
## arange사용 : np.arange(1, 5).reshape(1,4)
print(x)

# 🔴 4행 1열의 구조에서 1, 2, 3, 4를 값으로 가지는 배열 y 생성

y = np.array([1, 2, 3, 4]).reshape(4, 1)
## arange사용 : np.arange(1, 5).reshape(4,1)
print(y)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [162]:
# 🔴 배열 x를 동일한 값으로 4행으로 확장한 새로운 배열 생성

## 🔸 행 방향으로 배열 추가하기(세로길이 증가) 메서드 : np.append(arr1, arr2, axis=0) 💛 

new_x = np.append(x, x, axis=0)
print(new_x)

[[1 2 3 4]
 [1 2 3 4]]


In [163]:
## 🔸 new_x로 네 줄로 만들기

new_x = np.append(new_x, new_x, axis=0)
print(new_x)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [164]:
# 🔴 배열 y를 이용해서 4*4 형태로 만들기

new_y = np.append(y, y, axis=1)
print(new_y)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [165]:
new_y = np.append(new_y, new_y, axis=1)
print(new_y)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [170]:
## 체크체크

print(x)
print("----------")
print(y)
print("----------")
print(new_x)
print("----------")
print(new_y)

[[1 2 3 4]]
----------
[[1]
 [2]
 [3]
 [4]]
----------
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
----------
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [168]:
# 🔴 1행 4열 배열과 4행 1열 배열의 브로드캐스팅 연산(그냥 두 개 더하기)
x + y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [169]:
# 🔴 노가다로 만든 것을 더해보기 (append를 사용하는 경우가 빈번함)

new_x + new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

### 벡터 연산

- 요소들에 대한 연산을 벡터 연산을 처리하면, 일반적인 for반복문으로 연산 작업을 처리하는 것보다 월등히 뛰어난 처리 속도로 효율적인 작업 가능

In [176]:
# 🔴 0부터 시작해서 100000000개 요소를 가진 배열 생성

z = np.arange(100000000)
print(np_print(z))
print(z.size)


    type : <class 'numpy.ndarray'>
    shape : (100000000,)
    ndim : 1
    dtype : int32
    array data : 
 [       0        1        2 ... 99999997 99999998 99999999]
None
100000000


- 💛 해당 셀을 수행하는데 얼마나 걸리는지 확인해주는 time 명령어

In [180]:
%%time

# 해당 셀을 완전히 수행하는데 소요된 시간을 표시해주는 주피터노트북 명령어
# 셀의 가장 상단에 위치해야함(주석 포함해서도 가장 상단에 위치해야 함)
# 반복문을 통한 합계 (x변수에 저장한 넘파이 배열 자료 총합 구하기)
# 시간 단위 : 1s = 1,00ms(밀리 세컨드) = 1,000,000us(마이크로세컨드)

loop_result = 0
for i in z :
    loop_result += i
print(loop_result)    

<timed exec>:8: RuntimeWarning: overflow encountered in long_scalars


887459712
Wall time: 20 s


In [181]:
%%time

# 넘파이 배열에서 해당 배열의 총합 .sum()을 통해 구해보세요

z.sum()

Wall time: 39 ms


887459712